### ISSUE TITLE
New Map Algorithm and Storage

### ISSUE THREAD

**Issue by wnormandin** [Kiwi-FruitBird/Bastille#2]
# New Map Algorithm and Storage
1. Develop a grid display function (a la battleship example in codecademy)
  * The grid values should encode the MapTile subclass type
    * D = 'dungeon' type of Room subclass
    * T = 'throne' type of Room subclass
    * H = 'hallway' type of Room subclass
    * W = 'window' type of Room subclass
    * ' ' = Empty space for walls?
2. Each locus in the grid corresponds to a dictionary with several potential types of objects
  * Maptile - Each grid locus must contain a maptile of some type
  * Enemy - Hallway or Room MapTiles may contain an enemy 
  * Item - Hallway, Room, or Treasure Chests may contain an item
    * Items may generate when an enemy is defeated
  * Trap - Room, Hallway, or Treature Chests may be trapped
3. Example
  * The grid locus at (3, 7) is a Room subclass of type 'dungeon' with the following attributes
    * 15% chance of containing an enemy
    * 20% chance of containing a trap
    * Boss Enemy subclass not allowed
    * 20% chance of containing an item
    * Room level is 5, determining item, enemy, and trap power/damage
  * The dictionary at (3,7) would contain 

> {'enemy_rate':0.15, 'trap_rate':0.2, 'item_rate':0.2, 'room_lvl':5, 'restrictions':['no_bosses', 'no_gold'],
>   'attributes':{'intro_text':'You have entered a dark, damp room.\nAs your eyes adjust to the light,\n
>  you notice chains on the walls.', 'name':'dungeon_003'}}

  * The .csv file would contain 'D' in the 8th item of the 4th row (base 0 index)
  * This would call a "dungeon" generator function that creates the dictionary based on predefined ranges

> Dungeons spawn enemies between 10 and 20% (return random value between 10 and 20, divide by 100)
> Dungeons spawn with traps between 10 and 20% of the time
> Dungeons spawn items between 15 and 30% of the time
> Enemies may not be of the Boss subclass
> The room is level 5, seeding the damage of enemies/traps or the value of items

  * A similar generator function will exist for each type of MapTile, Item, Trap, Enemy, and Treasure Chest subclass

**Comment by wnormandin** [comment]
This will need to tightly correspond to the new class structure issue I am working on.  I can help you with the generators - they are basically like a function, except they use **yield** instead of **return**.  Each time a generator exits, *it stores the values of its local variables instead of destroying it*.  The next time the generator is called, it will continue where is left off, allowing you to do things like generate incrementing room names (**dungeon_001, dungeon_002**) each with unique attributes.

**Comment by Kiwi-FruitBird** [comment]
A template for how the view map action will work has been added to the actions and player scripts in the new_class dir. We discussed using a different method than appending a list for visited coordinates, so this was just thrown in as a reminder to include the final implementation of however we think would best work with the new world.py script after that is functioning.

**Comment by wnormandin** [comment]
### tiles.dat format
Following the convention, this will be a tab-delimited file with single quote as the quote character

> Child Class | Nice Name | Enemy Rate | Enemy Type(s) | Item Rate | Trap Rate | Chest Rate
>
> 'Room'	'Dungeon'	7	Melee,Sorcerer,Undead	0	0	0

### Room child class example
Invoking an instance of the Room child class will randomly select a room from the tiles.dat file

> \>>> from tiles_2 import *
> \>>> x = Room([0,0,1])
> \>>> print x
> A level 1 Hallway containing 1 enemy
> \>>> x = Room([0,0,1])
> \>>> print x
> A level 1 Dungeon containing 1 enemy
> \>>> x = Room([0,0,1])
> \>>> print x
> A level 1 Throne Room containing 2 enemies
> \>>> for i in x.enemy_list:
> ...     print i
> ... 
> A level 2 Royal Guard named royal_guard_003 in tile room_003
> Damage: 7
> Health: 36
>
> A level 0 Lich named lich_004 in tile room_003
> Damage: 9
> Health: 29

**Comment by wnormandin** [comment]
### Room object members
* Room.lvl
* Room.locus
* Room.name
* Room.nicename
* Room. enemy_rate
* Room.enemy_types
* Room.item_rate
* Room.trap_rate
* Room.chest_rate
* Room.enemy_list

**Comment by wnormandin** [comment]
[((0,0,0), 'S', 'room_003', Room Object with .name=='room_003'), (...]

This will be a list with each location containing the following :

(0,0,0) - the x/y and z(floor number) values for the grid locus

'S' -  The mini-map or map visualization code for this tile type

'room_003' - MapTile.name value for this location

Room Object... - The MapTile object in this location

**Comment by wnormandin** [comment]
@Kiwi-FruitBird once you get the Traps and Item Looting working, comment and close this issue out

**Comment by wnormandin** [comment]
Finishing in #4
